version: "3.9"
services:
  cashflow-keycloak:
    image: jboss/keycloak:latest
    container_name: cashflow-keycloak
    environment: 
      - PROXY_ADRESS_FORWARDING=true
    env_file: .env
    ports: 
      - 8092:8080

  cashflow-mysql:
    image: mysql:latest
    container_name: cashflow-mysql
    environment:
      - MYSQL_DATABASE=cashflow
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 5

  cashflow-docx:
    image: cashflow-docx-image:latest
    container_name: cashflow-docx

  cashflow-odata:
    image: cashflow-odata-image:latest
    container_name: cashflow-odata
    env_file:
      - .env
    depends_on: 
      cashflow-docx:
        condition: service_started
      cashflow-mysql:
        condition: service_healthy

  cashflow-ui5:
    image: cashflow-ui5-image:latest
    container_name: cashflow-ui5
    depends_on: 
      - cashflow-odata

  cashflow-nginx:
    image: cashflow-nginx-image
    container_name: cashflow-nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - cashflow-keycloak
      - cashflow-ui5