version: "3.3"
services:
  cashflow-keycloak:
    image: jboss/keycloak:12.01
    container_name: cashflow-keycloak
    env_file: .env
    volumes:
      - ./keycloak:/keycloak/imports

  cashflow-mysql:
    image: mysql:8.0.21
    container_name: cashflow-mysql
    env_file:
      - .env

  cashflow-docx:
    image: cashflow-docx-image:1
    container_name: cashflow-docx

  cashflow-odata:
    image: cashflow-odata-image:1
    container_name: cashflow-odata
    env_file: .env
    depends_on:
      - cashflow-docx
      - cashflow-mysql

  cashflow-ui5:
    image: cashflow-ui5-image:1
    container_name: cashflow-ui5
    depends_on:
      - cashflow-odata

  cashflow-nginx:
    image: cashflow-hosting-image:2
    container_name: cashflow-nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - cashflow-keycloak
      - cashflow-ui5
